name: Ejecutar descarga diaria

on:
  schedule:
    - cron: '0 12 * * *'  # todos los días a las 7:00 a.m. Colombia (UTC-5)
  workflow_dispatch:  # permite ejecutarlo manualmente

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Instalar dependencias
        run: pip install pandas requests prefect

      - name: Ejecutar script
        run: python descarga_diaria.py
